# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Josh\OneDrive\Documents\Transfer project\GUI\SelectionGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Selectionscreen(object):
    def setupUi(self, Selectionscreen):
        Selectionscreen.setObjectName("Selectionscreen")
        Selectionscreen.resize(1059, 735)
        Selectionscreen.setMinimumSize(QtCore.QSize(1059, 735))
        Selectionscreen.setMaximumSize(QtCore.QSize(1059, 735))
        self.label = QtWidgets.QLabel(Selectionscreen)
        self.label.setGeometry(QtCore.QRect(10, 10, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pbCreate = QtWidgets.QPushButton(Selectionscreen)
        self.pbCreate.setGeometry(QtCore.QRect(50, 270, 231, 71))
        self.pbCreate.setObjectName("pbCreate")
        self.pbSearch = QtWidgets.QPushButton(Selectionscreen)
        self.pbSearch.setGeometry(QtCore.QRect(310, 270, 231, 71))
        self.pbSearch.setObjectName("pbSearch")
        self.pbCollect = QtWidgets.QPushButton(Selectionscreen)
        self.pbCollect.setGeometry(QtCore.QRect(570, 270, 231, 71))
        self.pbCollect.setObjectName("pbCollect")

        self.retranslateUi(Selectionscreen)
        QtCore.QMetaObject.connectSlotsByName(Selectionscreen)

    def retranslateUi(self, Selectionscreen):
        _translate = QtCore.QCoreApplication.translate
        Selectionscreen.setWindowTitle(_translate("Selectionscreen", "Dialog"))
        self.label.setText(_translate("Selectionscreen", "Title"))
        self.pbCreate.setText(_translate("Selectionscreen", "make a booking"))
        self.pbSearch.setText(_translate("Selectionscreen", "search for booking"))
        self.pbCollect.setText(_translate("Selectionscreen", "Collect booking"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Selectionscreen = QtWidgets.QDialog()
    ui = Ui_Selectionscreen()
    ui.setupUi(Selectionscreen)
    Selectionscreen.show()
    sys.exit(app.exec_())
